/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./public/index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        primary: '#8d36aa',
        'primary-container': '#a951c5',
        'on-surface-variant': '#4f4350',
        'on-secondary-container': '#753b82',
        'on-secondary-fixed': '#340042',
        'tertiary-fixed': '#eae86e',
        'on-tertiary-container': '#434200',
        'on-primary': '#ffffff',
        'surface-bright': '#fff7fb',
        'primary-fixed-dim': '#f0b0ff',
        'tertiary-fixed-dim': '#cecb56',
        error: '#ba1a1a',
        'outline-variant': '#d2c1d2',
        outline: '#817381',
        background: '#fff7fb',
        'inverse-surface': '#362e36',
        'on-error': '#ffffff',
        'surface-tint': '#8d36aa',
        'secondary-container': '#f4aeff',
        'surface-container-high': '#f2e4ef',
        'inverse-primary': '#f0b0ff',
        'on-primary-fixed-variant': '#721790',
        secondary: '#83478f',
        'on-primary-container': '#0e0015',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#b2b03d',
        tertiary: '#636100',
        'surface-dim': '#e3d6e0',
        'on-primary-fixed': '#330044',
        'secondary-fixed-dim': '#f4aeff',
        'on-secondary-fixed-variant': '#682e75',
        'inverse-on-surface': '#faedf7',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#1d1d00',
        'surface-container-low': '#fdf0fa',
        surface: '#fff7fb',
        'primary-fixed': '#fbd7ff',
        'error-container': '#ffdad6',
        'surface-variant': '#ecdfe9',
        'surface-container-highest': '#ecdfe9',
        'secondary-fixed': '#fdd6ff',
        'on-background': '#201921',
        'surface-container': '#f7eaf4',
        'on-surface': '#201921',
        'on-tertiary-fixed-variant': '#4a4900',
        brand: {
          frame: '#40034F',
          neutral: '#7E747D',
          action: '#A951C5',
        },
        /** Amazon-style full-width page gutter (body under header) */
        marketplace: '#f0f2f2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        md: '16px',
        base: '4px',
        'margin-desktop': '32px',
        sm: '8px',
        gutter: '16px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        xl: '40px',
        lg: '24px',
      },
      fontFamily: {
        h2: ['Plus Jakarta Sans', 'sans-serif'],
        h1: ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        h3: ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        price: ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '700' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        h3: ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        price: ['20px', { lineHeight: '1', letterSpacing: '0', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        /** Prefer w-full + horizontal padding for marketplace layout; kept wide for legacy */
        page: 'min(100%, 1920px)',
      },
      keyframes: {
        toastIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        toastIn: 'toastIn 0.25s ease-out forwards',
      },
    },
  },
  plugins: [],
};
